spring.application.name=job-scheduler

# ==== Database (MySQL) ====
# Create the DB first: CREATE DATABASE jobscheduler;
spring.datasource.url=jdbc:mysql://localhost:3306/jobscheduler?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=omkar@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8090

# ==== JWT ====
jwt.secret=ThisIsA256BitSecretKeyForJWTSigningChangeInProdEnvironment123456
jwt.expiration-ms=86400000

# ==== Worker ====
worker.poll.batch-size=10
worker.thread-pool.size=10
worker.heartbeat.stale-threshold-seconds=30

logging.level.com.jobscheduler=INFO
